### PR TITLE
Document diagrams

### PR DESCRIPTION
**Pull request by Unicus-Tom**
The images arent in a good location. But I am unsure where each should go

### CODE REVIEW

**Review by gjersvik — CHANGES_REQUESTED** [review]
Please move all the diagrams away from doc root.  Too something like /docs/platform/diagrams/

**Comment by kribjo1968** [comment]
This looks good, I only have one comment. For User_Interaction_Flow diagram there are two questions describing flow from Azure Portal. Please look into it.

**Review by kribjo1968 — CHANGES_REQUESTED** [review]
This looks good, I only have one comment. For User_Interaction_Flow diagram there are two questions describing flow from Azure Portal. Please look into it.

**Review by Kris2ffer — APPROVED** [review]

**Review by gjersvik — APPROVED** [review]
Looks good now we only need some markdown that connects all these diagrams together but that sound to me like another task.

**Review by jonaspetersorensen — CHANGES_REQUESTED** [review]
Please add a paragraph in `setup-dev-environment.md` that describes what you used to generate the diagrams and how you have configured this (C4).

**Review by jonaspetersorensen — CHANGES_REQUESTED** [review]
Please rename "how-to-use.md" to "README.md".
The reason for this is that the file is hard to find among all the other ones in the same directory, especially when you do not even know that it is there or why it should be there.
GitHub will treat "README.md" as a html index file, meaning that the file will be instantly visible when a user browse the directory. This is a good way of hightligtning imporant information about the contents of that directory.

**Review by kribjo1968 — CHANGES_REQUESTED** [review]
RestApiComponents.puml and SepesContainer.puml are not available as png or svg. Please create.

**Review by jonaspetersorensen — APPROVED** [review]

**Review by kribjo1968 — APPROVED** [review]

**Pull request merged**
